### ISSUE TITLE
Google Summer of Code 2016

### ISSUE THREAD

**Issue by johndbritton** [github/gsoc#104]
GitHub is a mentoring organization for Google Summer of Code 2016. You can read more about the program and see the full timeline on the [official site](https://summerofcode.withgoogle.com/how-it-works/)

As a participating organization, we've created an [ideas list](https://github.com/github/mentorships/issues?q=is%3Aissue+is%3Aopen+label%3Aproject) that you can browse. We encourage potential students to use the ideas list as a starting point to discover projects and make proposals, but want to make it clear that we're open to project proposals outside of this list as well.

Each of the project ideas lists potential mentors as well as the official repository for the project. If you have questions or need help creating a project proposal, you can get in contact with those mentors via the project repository.

Feel free to [join chat](https://gitter.im/github/mentorships) or open issues here with general questions about GitHub's participation in Google Summer of Code.

cc/ @github/open-source-mentorships

**Comment by devkhan** [comment]
Can we have a general purpose chat on Gitter or something similar where all the students can discuss issues, questions, doubts, etc? 

Right now, every project's discussion happens on its own issue or project chat. We can have a common chat room and maybe also a chat logo on the **README** of this repo. I know we can open an issue for questions but instead of having distributed discussions, won't it be nice if we have it all centralized. All the mentors and students can join that room.

Can we do this?

**Comment by bkeepers** [comment]
@devkhan thanks for the suggestion. We are hanging out at https://gitter.im/github/mentorships.

/cc #113

**Comment by benbalter** [comment]
@johndbritton can this be closed so it does not appear as an [available program](https://github.com/github/mentorships/labels/program)?

**Comment by pratyush247** [comment]
What about 2017 i passionately want to do gsoc can anyone help me how to get gist of projects and how to start with one without wasting time ?
