### ISSUE TITLE
Idea for Homebrew: livecheck mechanism

### ISSUE THREAD

**Issue by youtux** [github/gsoc#11]
I would like to discuss a proposal for Homebrew: a mechanism to check whether a formula is outdated with respect to the upstream version.
I have already started a conversation at Homebrew/homebrew#33433, and I think the GSoC could be an occasion to re-propose this feature. I have already created an external command ([homebrew-livecheck](https://github.com/youtux/homebrew-livecheck)) that tries to achieve this, but it is still an alpha version and it is very fragile.

I would like to know if this could be a subject of interest for the Homebrew project.

**Comment by youtux** [comment]
@mikemcquaid Maybe I should have mentioned you.

**Comment by MikeMcQuaid** [comment]
@youtux Watching this repo now, forgot to do so earlier. I wouldn't stop you proposing that but I would probably favour one of the existing proposals. That said, if you could create a livecheck which would require minimal maintenance (e.g. comfortably run on a free Heroku worker), could maybe autosubmit PRs that might be of interest. My concern would be it might not be quite a big enough project for the whole summer but a good proposal could definitely convince me otherwise.

**Comment by youtux** [comment]
Thank you for your feedback! Yes, it would be not too much difficult to actually take the whole summer.
