### ISSUE TITLE
idea: Adding IDE Deployment plugins like FTP, SFTP which can make deployment of apps easier. 

### ISSUE THREAD

**Issue by vik-y** [github/gsoc#27]
I like this feature which is offered by JetBrains PHP IDE. It helps to easily deploy your website and also keep your code base in sync - but so does git along with a version control system but this feature can be very useful, your views/suggestions? 

Also there's a large scope for command line integration for directly compiling and running the code. In the summer I'd like to work on these ideas.

**Comment by johndbritton** [comment]
Hi @vik-y, I'm guessing you're interested in working on Atom. The idea you've suggested sounds interesting, but it's not very well defined.

In order to make a successful proposal, you'll need to clearly state the scope of what you'd like to accomplish in the project and make a plan for implementing it.

**Comment by vik-y** [comment]
Hi @johndbritton , 
Yes, I was talking with respect to atom itself. This feature is something which I often use in Jetbrains IDE and would like to implement the same in atom also. I will get back to you with how exactly I am planning to do it. 
Thanks :)

**Comment by bkeepers** [comment]
Thanks for your interest in Atom! The application deadline is passed, so I'm going to close this. Let us know if you have any other questions.
