### ISSUE TITLE
Improving Atom's parser performance: Changing the regex engine.

### ISSUE THREAD

**Issue by prasoon2211** [github/gsoc#36]
@kevinsawicki 

Hi. I went through the [issue 979](https://github.com/atom/atom/issues/979) and left a [comment](https://github.com/atom/atom/issues/979#issuecomment-77703711). Please read it (and the various links mentioned within) - there, I've made a case for changing the regex engine. Let me what you think of the idea.

Thanks!

**Comment by randomPoison** [comment]
From what I can tell Oniguruma's big feature is that it can handle a wide variety of different encodings, which means atom can parse just about any kind of file with out special handling. RE2 [only handles UTF-8 and Latin-1](http://swtch.com/~rsc/regexp/regexp3.html), so that would require some work on atom's part to handle other encodings.

I'm guessing that would still be worthwhile, though, since the cost of converting to UTF-8 when loading or saving a file is probably less expensive than a slow regex implementation.

**Comment by randomPoison** [comment]
Since @zcbenz pointed out that Oniguruma is used only for its regex syntax, it would probably be a good idea to build a comparison of the regex syntax used in TexMate and what's supported by RE2. If it wouldn't take too much to handle the differences then the speed improvements would likely be worth it.

**Comment by ljfio** [comment]
Having a brief look at the language-perl grammar's [regex](https://github.com/atom/language-perl/blob/master/grammars/perl.cson#L151) you can see that RE2 doesn't [support](https://github.com/google/re2/wiki/Syntax) "before text matching" and also "after text matching".

**Comment by bkeepers** [comment]
Thanks for your interest in Atom! The application deadline is passed, so I'm going to close this. Let us know if you have any other questions.
