### ISSUE TITLE
Homebrew: Allow prioritisation of taps

### ISSUE THREAD

**Issue by CNA-Bld** [github/gsoc#42]
Hi. I am Huang Yue from the School of Computing, National University of Singapore. I am now doing my bachelor degree in Computer Science and I am 'somewhere between second and third year' since I am trying to graduate in 3 and a half year.

I am particularly interested in the proposal of about prioritization of taps.

I have used Homebrew for a while and I have read a portion of its code. As far as I am concerned, implementing this will actually make a great change in Homebrew's structure.

So far I realized that currently we do not actually have 'meta information' of taps and thus they cannot be managed efficiently. I suppose that the expected outcome of this proposal is actually to implement a better structure for taps so they work more similar to 'sources' in other package managers like `apt-get` or `yum`. (And after that, allowing prioritization is easy, much like how `yum-plugin-priorities` works.)

@mikemcquaid  Am I thinking the problem correctly? If so I am probably going to design and propose an architecture of a new version of taps, as well as analyzing how much changes I need to make. Thank you very much for your help!

**Comment by MikeMcQuaid** [comment]
> @mikemcquaid Am I thinking the problem correctly? If so I am probably going to design and propose an architecture of a new version of taps, as well as analyzing how much changes I need to make. Thank you very much for your help!

Yep, I think you are. Homebrew currently tries to use filesystem layout and environment variables rather than configuration files so ideally we'd use those approaches where possible. I'd think that this should take the form of arguments to the `brew tap` command rather than requiring users to manually edit any files.

Something that would be a good start before making a proposal is also submitting a few PRs to Homebrew (if you haven't already). Simple things like fixing `brew audit` warnings or version upgrades would be a great start. Let me know if that answers your questions, thanks!

**Comment by CNA-Bld** [comment]
Oh I understand. I think I am going to fix some `audit` warnings to get more familiar with the internal design of Homebrew now. Thank you!

**Comment by MikeMcQuaid** [comment]
Closing this out as I assume I've answered your questions. Feel free to ask more if I haven't!
