### ISSUE TITLE
Homebrew: Why `brew versions` was removed from official repo?

### ISSUE THREAD

**Issue by liudangyi** [github/gsoc#53]
I think it would be a great feature if homebrew supports `brew install ruby --version=2.2.0`.

I find that homebrew once supported `brew versions` to list all versions of a formula so that you can manually checkout and install a special version. And I'm wondering why it's removed now.

**Comment by MikeMcQuaid** [comment]
`brew versions` was removed because it was buggy and hard to support. As it relied on Git revisions it was impossible to fix issues with older versions of formulae. The replacement is using `homebrew/versions` which, although more annoying to contribute to, provides a much better user experience all round.
