### ISSUE TITLE
Homebrew: Some potential improvements

### ISSUE THREAD

**Issue by liudangyi** [github/gsoc#55]
1. Formulae should be able to interpose the link period, i.e., decide which directory to link or not.
2. Besides `uninstall`, homebrew should introduce a `purge` method that removes all files, including some generated files under `etc` / `var` and downloaded files under `lib`.

**Comment by MikeMcQuaid** [comment]
We've discussed both of these in the past and don't want to do them.

For 1. it adds a lot of complexity which can be instead solved by just changing the formulae structure to e.g. install everything under `libexec` and make relevant symlinks.

For 2. we don't want to delete data like e.g. MySQL databases or configuration files on `uninstall` because people may (and probably will) want them after reinstall. Additionally, we don't have an `uninstall` hook so people can remove packages manually without using Homebrew.

I think it's better to focus on the suggested proposals or others that feature requests that are already on the Homebrew issue tracker.

Thanks!

**Comment by liudangyi** [comment]
Thank you for your patience.
