### ISSUE TITLE
proposal review channel

### ISSUE THREAD

**Issue by ghost** [github/gsoc#57]
Since the official application period opens on 16th, will GitHub open an official medium for students to get their proposal reviewed for completion before students submit their proposal to Google? 

This is important as GitHub hasn't provided an official template for proposals, so ideally it would help if students had a medium to make sure that their proposal was complete, in the sense that all information that GitHub expects in a _good_ proposal is there, as well as potential mentors can provide some valuable feedback on any additional information that students can add to their proposal, and increase their chances of getting selected for GitHub.

If not, is it _advised_ for students to email potential mentors their proposals, and get valid criticism and feedback, @mikemcquaid agreed to this in #46, which is good news... for Homebrew, maybe someone from atom, linguist and hub teams can also agree to review proposals.

Cheers!

/cc @zcbenz @kevinsawicki @jlord @bkeepers @mislav

**Comment by shana** [comment]
> Since the official application period opens on 16th, will GitHub open an official medium for students to get their proposal reviewed for completion before students submit their proposal to Google?

We're working on getting an official proposal template up for the students to fill out, very soon now. Students won't be submitting proposals to Google, they'll be submitting proposals to us via the Google's website, and they can edit and refine the proposal after they submit it. The Google app allows private and public comments on the proposal, as well as voting and rating, and we control how those things impact our proposal selection.

Students typically delay sending in proposals until very late in the application period. This is a problem because the proposals need to be in the system, rated and have mentors assigned to them by the end of the application period. This means that proposal evaluation needs to be done on an ongoing basis as they come in to the system, so the sooner the proposals come in, the more time we will all have to give feedback and have the student improve it.

This can of course be done outside of the Google app, but if that happens, I recommend doing it on a private gist. Avoid having proposals in the public and open, for obvious reasons.

There's also the questions of how many slots we will potentially get from Google. Traditionally, first time orgs don't get that many slots, so we'll probably have to make a lot of tough decisions when selecting proposals, and if they're in the system earlier rather than later, it'll be easier to have an idea of the overall quality of proposals and how to distribute the available slots.

> If not, is it advised for students to email potential mentors their proposals, and get valid criticism and feedback, @mikemcquaid agreed to this in #46, which is good news... for Homebrew, maybe someone from atom, linguist and hub teams can also agree to review proposals.

While students are encouraged to get in touch with the communities early, GitHub has such a large audience that we predict there's going to be a large number of students showing up. Having them all contact every potential mentor directly as a first step towards making a proposal is going to be potentially overwhelming for mentors. I would be careful in advising direct email contact with potential mentors unless there's already other venues of communication ongoing (forums, issues, etc) and the mentor decides email is a good venue for that particular student. 

The more people that are available to review proposals, the better! You can sign up on the gsoc website as a mentor even if you're just wanting to help review proposals and not actually mentor - not everyone that wants to mentor will get to mentor (depends on how many slots we get), but we can use every pair of eyes we can get to triage and review proposals.

**Comment by ghost** [comment]
Thanks @shana, that cleared everything up, closing this in favour of #58

**Comment by octref** [comment]
@shana 
Sorry, this is my first time applying for GSOC so I'm not familar with this process. 
I have a few questions for you.

> The Google app allows private and public comments on the proposal, as well as voting and rating, and we control how those things impact our proposal selection.

Is it that all proposals will be visible to applicants, or just mentors?

> The more people that are available to review proposals, the better! You can sign up on the gsoc website as a mentor even if you're just wanting to help review proposals and not actually mentor - not everyone that wants to mentor will get to mentor (depends on how many slots we get), but we can use every pair of eyes we can get to triage and review proposals.

I'm confused. Are you suggesting that we, student applicants, should sign up as mentors and help review proposals? Doesn't that conflict with your applicant status?

**Comment by shana** [comment]
Hi @octref 

> Is it that all proposals will be visible to applicants, or just mentors?

Proposals are visible only to mentors of the organization.

> I'm confused. Are you suggesting that we, student applicants, should sign up as mentors and help review proposals? Doesn't that conflict with your applicant status?

This line was meant for mentors, not students :) You can't actually sign up to be both a mentor and a student iirc.

**Comment by octref** [comment]
@shana 
Thanks for clarification! BTW your nick is cool :wink:
