### ISSUE TITLE
Why Linguist uses so many Vendors for Syntax Highlighting 

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#70]
Linguist is using so many vendors for syntax highlighting as the below link says :
https://github.com/github/linguist/tree/master/vendor/grammars
Why Linguist does not use any single package manager for syntax highlighting.

**Comment by rootAvish** [comment]
Those are grammars.

**Comment by pchaigno** [comment]
Linguist was using [Pygments](http://pygments.org/) before, a generic syntax highlighter. It is now using TextMate/Sublime Text grammars because it is much faster. There isn't a single highlighter for these grammars as far as I know. I personally think it's best to rely on multiple grammars anyway because that means each grammar can be maintained by developers who actually use it.

**Comment by bkeepers** [comment]
> I personally think it's best to rely on multiple grammars anyway because that means each grammar can be maintained by developers who actually use it.

This is definitely one of the huge advantages. Instead of depending on one library to be good at everything, we can pick the best grammars that people already use in their editors.
