### ISSUE TITLE
support for 'blue-sky proposals'

### ISSUE THREAD

**Issue by ghost** [github/gsoc#8]
Most gsoc orgs allow students [to](https://github.com/jquery/gsoc/wiki/GSoC-2015-Ideas-List#blue-sky-proposals) [come](https://wiki.phpmyadmin.net/pma/GSoC_2015_Ideas_List#Your_idea) [up](https://gcc.gnu.org/wiki/SummerOfCode#Other_projects) with their own project ideas, that should be innovative but should also be restricted to specific domains. Who should prospective applicants get in touch with to discuss their ideas, and **exactly** which GitHub open source projects are within scope for such ideas ?

**Comment by johndbritton** [comment]
> Who should prospective applicants get in touch with to discuss their ideas

You're in the right place for that, just open an issue here and discuss away.

> and exactly which GitHub open source projects are within scope for such ideas?

All of the projects in the readme are definitely within scope, as we have mentors lined up for those projects. You can come up with your own idea and propose it for one of those in addition to proposing something from the ideas list.

If there's another GitHub maintained open source project that you'd like to propose a project on, feel free to do so and if it's a good proposal we'll try and get a mentor. We don't have an exhaustive list of all the open source projects you could propose for, because we don't have mentors lined up for them all.

**Comment by bkeepers** [comment]
To add to @johndbritton's reply, feel free to open an issue in this repo to discuss specific project ideas. We should be able to help you figure out if it's even feasible to find a mentor for a specific project before you go through the trouble of submitting your proposal.

**Comment by ghost** [comment]
Got it ! Thanks
